### ISSUE TITLE
Allow one to specify port when using --local

### ISSUE THREAD

**Issue by smbuthia** [medic/medic-conf#256]
Currently, `--local` defaults to `localhost:5988` however the default docker set up uses port `80`. It would be nice to have a way to specify a port other that 5988 when working with `--local`

**Comment by SCdF** [comment]
The default docker I think uses 443 not 80, but it definitely also uses a different username (`medic` as opposed to the more traditional `admin`), so it doesn't fit in lots of ways.

Maybe we need a dev local and a docker local?

**Comment by smbuthia** [comment]
I think having a dev local and docker local makes sense.

**Comment by kennsippell** [comment]
Are we considering adding an interface like `--docker --user=usr --password=pass`? What do you think of just using `--url=https://usr:pass@localhost` for this scenario? I think it is reasonable because it follows existing simple auth standards for proving username/password, it is more generic to accomodate other scenarios, it requires less key strokes to type out, it is more transparent as to how medic-conf uses the information under the hood, and it is easier to maintain/understand because there are fewer interfaces to medic-conf.  

imo it seems preferrable to have a small number of generic interfaces to medic-conf, instead of many scenario-specific interfaces - particularly since this is a developer tool

interested in your thoughts @smbuthia!

**Comment by smbuthia** [comment]
>I think it is reasonable because it follows existing simple auth standards for proving username/password, it is more generic to accomodate other scenarios, it requires less key strokes to type out, it is more transparent as to how medic-conf uses the information under the hood, and it is easier to maintain/understand because there are fewer interfaces to medic-conf.

I think these are valid points @kennsippell. I also like the consistency that will result from having it this way.

Adding an interface like `--docker` would make sense when using consistent default username and password which I think might not always be the case.

I'm in favor of `--url=https://usr:pass@localhost` or perhaps `--url=https://<usr>@localhost:<port>` with a prompt for password.

**Comment by kennsippell** [comment]
These features are currently supported.
