### ISSUE TITLE
Warn about deprecated transitions when uploading app-settings

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic-conf#269]
There are a number of deprecated transitions in `cht-core`, each with it's own deprecation "version":

 - `update_notifications` deprecated since **3.3.0** in favor of `muting` 
 - `update_sent_forms` deprecated since **3.7.0** due to the refactor of Reminders
 - `generate_patient_id_on_people` deprecated since **3.8.0** in favor of `generate_shortcode_on_contacts`
 
`medic-conf` could warn, pre-upload (?), when a deprecated transition is enabled in app_settings, depending on the version of the app the instance is running. 

Questions to consider:

Should the deprecation table be hardcoded in medic-conf?
Should we have an API endpoint that returns the list of deprecated transitions?

**Comment by dianabarsan** [comment]
This is ready for AT. 
Both cht-core and medic-conf have updates to solve this issue. 
Updates to `cht-core` can be found on the  `269-warn-deprecated-transitions` branch, while the upadtes to `medic-conf` can be found on the `269-log-warning-deprecated-transitions` branch.

**Comment by newtewt** [comment]
@latin-panda I think this looks good. I wonder if this would be worth adding a check if that transition actually exists instead of causing all transitions to be disabled but is probably a separate issue. 

Confirmed warning logs in apps about deprecation
Confirmed warning logs in medic-conf while uploading settings, 
Confirmed medic-conf works with old versions
Confirmed cht-core works with old version of medic-conf.
Confirmed transitions still work.
