### ISSUE TITLE
Keep our apps and configurations in sync with `medic-conf` version

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-conf#288]
**Describe the issue**
At the moment, the latest `medic-conf` version is 3.0.6, but cht reference app is using 3.0.4 and standard is using 3.0.0.
 When running `medic-conf`, we get a warning like in the screenshots below...
While it always possible to just ignore the warning, it would be a good and safe practice to keep these versions consistent..

![image](https://user-images.githubusercontent.com/6979995/67057960-3149c600-f1af-11e9-9c73-0b976ae0ec67.png)

![image](https://user-images.githubusercontent.com/6979995/67058131-fac07b00-f1af-11e9-85bd-c65ac0e3a5b4.png)

**Comment by billwambua** [comment]
So the implemented rules are:

So the rules for medic-conf version checking.:

1. Newer medic-conf is ok as long as in the same Major version and a lesser patch version. No warning. So if medic-conf version is `3.1.2`, project version can be `3.0.0 - 3.1.2`. Major version differing should always give an error. A suggestion to align the project version and local version as well as the commands to run are given.

So the reason for not allowing a different major release to work with each other is simply because major releases usually introduce breaking changes i.e 3.x vs 4.x

The reason for not allowing an older local medic-conf patch release to work with a later project patch version e.g 3.0.2(local medic-conf) to work on 3.0.3(project): is is that there are many releases which fix important bugs which are released as patches and not minor versions e.g https://github.com/medic/medic-conf/commit/eebb5962562d300f6f703f3ed6e156da4e54d7c2 which fixed an important issue in the purging feature.

**Comment by garethbowen** [comment]
Ready for AT in `billwambua:288-semver-version-check`

**Comment by ngaruko** [comment]
There are errors showing when we run this version of medic-conf on the branch? Did you want to have a look at this @billwambua ?
![image](https://user-images.githubusercontent.com/6979995/78634186-81e8e300-78f7-11ea-8a7c-9770c9a6528a.png)

```

ERROR targets.js invalid schema: 
ERROR "[2].dhis" is not allowed. Value is: "[object Object]" 
ERROR "[5].dhis" is not allowed. Value is: "[object Object]" 
ERROR Error: Declarative configuration schema validation errors
    at module.exports (/Users/bede/Medic/bill-medic-conf/src/lib/validate-declarative-schema.js:178:11)
    at compileDeclarativeFiles (/Users/bede/Medic/bill-medic-conf/src/lib/compile-nools-rules.js:45:3)
    at compileNoolsRules (/Users/bede/Medic/bill-medic-conf/src/lib/compile-nools-rules.js:30:12)
    at compileAppSettingsForProject (/Users/bede/Medic/bill-medic-conf/src/fn/compile-app-settings.js:45:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.compileAppSettings [as execute] (/Users/bede/Medic/bill-medic-conf/src/fn/compile-app-settings.js:22:19)
    at async module.exports (/Users/bede/Medic/bill-medic-conf/src/lib/main.js:185:5)
    at async /Users/bede/Medic/bill-medic-conf/src/bin/medic-conf.js:11:18 
```
and one runs the command with ` --debug`, there are a couple of warnings, but it goes through :
```

WARN targets.js invalid schema: 
WARN "[2].dhis" is not allowed. Value is: "[object Object]" 
WARN "[5].dhis" is not allowed. Value is: "[object Object]" 
INFO Packaging nools 

```

**Comment by garethbowen** [comment]
@ngaruko That error seems unrelated to the code that has changed. Are you trying to upload 3.9.0  config? Try using the 3.8.0 version so the schema validation understands it.

**Comment by ngaruko** [comment]
@garethbowen Yes 3.8.x does not complain about this.

**Comment by ngaruko** [comment]
LGTM
On `master`
![image](https://user-images.githubusercontent.com/6979995/79275252-f2948e80-7ef9-11ea-9607-4b7ea4374f11.png)

On Bill's branch 
![image](https://user-images.githubusercontent.com/6979995/79275362-1d7ee280-7efa-11ea-8886-57c4d3c8069b.png)
Back to you @billwambua for a merge!

**Comment by garethbowen** [comment]
Merged. Thanks @billwambua !
