### ISSUE TITLE
Support for declarative configuration and legacy configuration to be deployed together

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-conf#309]
**Concept**
Siaya looks like it will take ~6-8 weeks of full-time work for two people to migrate legacy to declarative. Muso was ~4 weeks of full-time effort for a core dev (me). BRAC migration is currently at ~5 weeks to migrate contact summaries + targets (no tasks, no test pass). These migrations are de-stabilising since the app is being re-written. 

The "all-or-nothing" nature of the declarative configuration system means that projects need to halt their work, re-write their configuration, and de-stabilize the whole system all at once when the configuration releases. This is difficult to convince partners to invest in, difficult to fundraise for, etc. If legacy technical partners could do piecemeal migrations to the declarative style, the burden of the migration could be spread out over many sprints, multiple test passes, multiple small releases that are less destabilizing.

**COVID**
Our current COVID response strategy is based on the use of [COVID reference applications](https://github.com/medic/config-covid). These reference applications are written in declarative configuration. Reference apps serve as demos and when projects commit to deploying the reference workflow, the reference app is wired to the project configuration and deployed along-side it. This strategy is based on the concept that reference implementations can be re-used, and that the reference configuration can be easily duplicated or possibly maintained from a single shared configuration.

Given that reference applications are written in declarative configuration, how do we deploy them for projects using legacy configurations? 

**Proposed Solution**
Medic-conf could support a "hybrid mode" for projects using the legacy rules.nools.js format together with the declarative configuration system. Move the code that runs inside the rules.nools.js template into a file which is included into the declarative webpack bundle. Merge the target.json data sources. Upload the tasks.json to app settings.

The alternative for COVID is that app builders need to port the COVID reference application written in declarative to the legacy system and maintain two copies of the implementation.

**Comment by MaxDiz** [comment]
In the scenario described above, deployments are required to support both standard and declarative configs when implementing a reference workflow. It's a huge drain on TL resources and unsustainable for the rapid turnaround required for covid response. Adding to v3.10 consideration

**Comment by garethbowen** [comment]
One workaround for this is for a reference legacy configuration to be developed or compiled from the reference declarative configuration. This way the legacy configurations can append the legacy reference app `nools.rules.js` to their own and it should just work.

**Comment by kennsippell** [comment]
@garethbowen Would you please propose this concept to the #covid-workflows-squad? cc @michaelkohn @helizabetholsen

**Comment by michaelkohn** [comment]
I can definitely see how it would be useful for projects to be able migrate in smaller chunks. I don't know how much dev effort it would take to do that (support both legacy and declarative) but we'd want to weigh that against the number of projects still using legacy config since at some point that number should be 0 (I'm assuming all new projects use declarative).

I don't think COVID demo apps should weigh heavily on our decision either. The demo apps have no targets, the contact summaries were only brought to the point of demo-ability, and there really aren't that many tasks defined (2 or 3 for EBS and 3 or 4 for CT).  Again, I don't know how much effort it takes to convert them manually, but there aren't that many things that would need to be converted so it might be easier to just manually convert them. The reality is... integrating any of these assets into an existing/legacy project would require testing and surgery anyway (you wouldn't be able to just take the demo app contact summary and overwrite a project's existing contact summaries).

**Comment by kennsippell** [comment]
At this point it seems safe to remove the COVID label from this issue since no project's covid interventions seem to align close enough with the reference apps for this to be needed imminently for a COVID response.

**Comment by MaxDiz** [comment]
@kennsippell is it safe to remove from v3.10 release as well?
We can continue discussion on reference app alignment with project deployments on slack.
