### ISSUE TITLE
Can't create task action with type "contact"

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic-conf#358]
**Describe the bug**
According to this issue: https://github.com/medic/cht-core/issues/1505 , tasks should support actions with type `contact` that, when clicked, redirect the user to a contact creation form. 
A typo in the [schema](https://github.com/medic/medic-conf/blob/master/src/lib/validate-declarative-schema.js#L125) doesn't allow to set the type to `contact`, and a bug in [task emitter](https://github.com/medic/medic-conf/blob/master/src/nools/task-emitter.js#L158) is hardcoding the action type to `report`. 

**To Reproduce**
1. Create a task with an action of `contact` type.
2. Observe error when building app settings.

If you edit medic-conf and change the schema to allow `contact` actions, when tasks are actually generated, their type will always be `report`.

**Expected behavior**
Schema should not throw errors and generated task actions should have correct `contact` type. 

**Environment**
- medic-conf version: 3.2.1
- cht-core version: 3.10.x

**Comment by garethbowen** [comment]
I'm not sure if this feature is used, but it seems like a quick win to patch it up.

**Comment by mrsarm** [comment]
### Current status

- I fixed the typo and schema issues suggested by @dianabarsan, branch https://github.com/medic/medic-conf/tree/358-fix-contact-task-action , still need some improvements in the schema validations before PR, but with the changes I could successfully create a "contact" action visible in the UI under the "Tasks" tab.
- The problem now is that the action doesn't work in the UI, clicking the action triggers the form creations but the UI does not display the form. As far I could debug, the Agular contact controller is called without the basic scope variables needed: parent and contact type variables are undefined and null, and the last one cause an exception in the controller code. Also the URL for the form creation is not OK, but not sure whether it is because the lack of the scope injection.

  ![358-contact-action-form-error](https://user-images.githubusercontent.com/1608415/92405098-4b63fe00-f10b-11ea-962c-b8e4016fc97c.png)



Maybe I going to pause the UI fix until the Angular 10 migration is done.

**Comment by dianabarsan** [comment]
@mrsarm 
Your task is not passing the correct context to Webapp, and that's why you are seeing this.

**Comment by dianabarsan** [comment]
Have a look at how we are redirecting to the contact form when loading such a task: 
https://github.com/medic/cht-core/blob/master/webapp/src/js/controllers/tasks-content.js#L187

and what parameters the state expects: 
https://github.com/medic/cht-core/blob/master/webapp/src/js/router.js#L215

This is also described in the original issue https://github.com/medic/cht-core/issues/1505. 

No UI changes should be needed.

**Comment by mrsarm** [comment]
So my I understanding of what you said @dianabarsan is that the task may not be created well (with the parent id and contact type set) or not processed well by the code that triggers the action when clicking. I'll check.

**Comment by dianabarsan** [comment]
When I tested this out, a correct task did open the expected contact creation form.

**Comment by mrsarm** [comment]
:thinking: maybe I did not create it properly, could you provide more detail of what kind of task did you create?

If it working, only rest to improve a bit the code to validate the schema better, because I removed the "required" constraint for the "form" field, but should be required if `"type" : "report"`. I'll add the patch soon.

**Comment by garethbowen** [comment]
@dianabarsan Can you please provide the config you used to create this task?

**Comment by dianabarsan** [comment]
```
{
    name: 'patient_create',
    icon: 'icon-person',
    title: 'patient_create',
    appliesTo: 'contacts',
    appliesToType: ['clinic'],
    appliesIf: function () {
      return true;
    },
    resolvedIf: function () {
      return false;
    },
    actions: [
      {
        type: 'contact',
        form: 'home_visit',
        modifyContent: function (content, contact) {
          content.type = 'person';
          content.parent_id = contact && contact.contact._id;
        }
      }
    ],
    events: [
      {
        id: 'creation-follow-up',
        start: 3,
        end: 7,
        dueDate: function (event, contact) {
          return contact.contact.reported_date;
        }
      }
    ]
  },
```

**Comment by garethbowen** [comment]
@mrsarm Is this all you need to get this issue ready for AT?

**Comment by mrsarm** [comment]
I think I tested what Diana passed on that time but didn't work, but likely it was because some configuration from my side and then started to work in the migration pausing this issue.

As soon I can start work on this again I'll re-check.

**Comment by dianabarsan** [comment]
Ready for AT on `358-fix-contact-task-action`

**Comment by newtewt** [comment]
Tested both creating contacts and using reports for the task action. I believe this is ready to merge.

**Comment by garethbowen** [comment]
@mrsarm I think this is ready to merge - can you merge and close please?

**Comment by mrsarm** [comment]
Sorry, it was merged but I forgot to close the ticket.

**Comment by mrsarm** [comment]
Oh, my mistake, the PR merged was the documentation one, merging the actual code...
