### ISSUE TITLE
Before pushing config check if the git repo needs a pull or a push

### ISSUE THREAD

**Issue by henokgetachew** [medic/medic-conf#64]
It would be great to have a warning like `There are changes in the upstream that you need to pull.  Are you sure you want to push config? (y/n)`

**Comment by alxndrsn** [comment]
Interesting!  An additional option would be to warn if you have local changes to the version stored in git.  Would that also be helpful?

**Comment by garethbowen** [comment]
Ready for AT on `64-git-check`

**Comment by mrsarm** [comment]
Move it back to _In progress_ so I can add extra checks noted in the PR.

**Comment by garethbowen** [comment]
Ready for AT again in `64-git-check`

**Comment by abbyad** [comment]
@medic/quality-assurance, let's make sure to have folks from the app services team involved in AT of this issue.

cc @kennsippell

**Comment by kennsippell** [comment]
The original issue specifies that it would be nice to check for upstream files, and poses the question "Would that also be helpful?" for checking local files.  it seems the PR does check for local files. 

In my experience, it is common to upload unstaged or uncommitted files. For example, it is fairly common to use "watchers" together with medic-conf to upload automatically every time a file changes (for example [here](https://github.com/medic/config-muso/blob/master/package.json#L10)). This is based on the idea that it is productive for every file change to be uploaded immediately (sort of the opposite of the expectation here).

How was that addition check decided on? What perceived value does that add? @mrsarm

**Comment by mrsarm** [comment]
Hi @kennsippell ,

>  it seems the PR does check for local files.

Yes, it does, although it does not prevent the user do upload of the config, it just require confirmation. I took for granted that the decision to make the changes was already decided and not an open discussion, sorry. I can change the code to just warn about the untracked and modified files but don't interrupt the upload process, what do you think @abbyad @garethbowen ?

> For example, it is fairly common to use "watchers" together with medic-conf to upload automatically every time a file changes

There is another [PR](https://github.com/medic/medic-conf/pull/343/files) that will prevent the need for confirmation passing the `--force` argument, although if merged, we would need to adapt this PR to use the new module `user-prompt` defined there.

**Comment by kennsippell** [comment]
Are you comfortable holding for a day or two? Let's get a quick round of UAT and decide whether any adaptation is desired. It's possible you've got it right as-written.

**Comment by mrsarm** [comment]
Sure, no rush, and I really want to merge it with [pull/343](https://github.com/medic/medic-conf/pull/343/files) if we decide to move forward with the current approach, so better to wait until that PR is merged.

**Comment by abbyad** [comment]
There appears to be a significant difference between working on a production vs dev instance. @kennsippell what is the workflow for updating production instances? Is there a instituted requirement that the config is committed to GH if any change is made to the production instance? How should these two scenarios be handled differently?

**Comment by derickl** [comment]
Good stuff @mrsarm!

Just wanted to echo @kennsippell's sentiments regarding someones workflow in testing environment. Uncommitted files will not be a big issue. It's part of the iteration process. Seeing warnings about that would be unnecessary also given the list could spill over to more than a handful of files.
 
However I really like the new visibility about commits missing in local and should help in limiting cases of overriding changes on an instance due to missing commits.

Could the change about uncommitted files be behind a flag? Say prod vs testing? Unfortunately that's one more thing to remember but we could choose a sensible default.

**Comment by billwambua** [comment]
Just to reiterate @derickl 's reiteration. The warning which shows when any file in the local git repo is not committed or staged would be more useful when working in a production instance rather than a testing instance. 

In a testing instance, it would be an extra step especially when one is trying to do a quick change and upload.

**Comment by mrsarm** [comment]
@derickl @billwambua @kennsippell ,

I just merged the latest changes from master that added the [--force argument](https://github.com/medic/medic-conf/issues/307) to allow the user to bypass the confirmation dialogs, so using the command with the `--force` argument will only warn the user about the untracked changes or the upstream changes, but pushing the configuration without intervention.

Is that enough for the use cases you mention?

Do you think may worth to add a new argument `--skip-check-git` to skip all together the checks done by this action or at least the upstream check that may delay the execution of the script because the access to the git upstream through the network?

**Comment by billwambua** [comment]
@mrsarm I've tested the PR and it looks and works good.

@mrsarm IMO, yes: a way to skip the checks would be useful.

**Comment by derickl** [comment]
Sorry for the delayed response @mrsarm. Adding the option to skip would be useful.

**Comment by garethbowen** [comment]
Thanks for the feedback Kenn.

@mrsarm Is there any simple way to just check the current directory? I can't think of a git command for this, but I imagine we could implement a regex fairly easily?

@kennsippell Do you think there's value in attempting to detect production vs non-production environments and having much looser validations (like ignoring this one) for non-production? There are a whole class of validations that could just be warnings (or ignored altogether) for non-production environments.

**Comment by kennsippell** [comment]
Yes, this seems like a useful validation step for production deployments. 

My opinion is that having medic-conf know if configuration is being pushed to a production instance would be useful in medic-conf (for this validation and for other validations).

**Comment by mrsarm** [comment]
> This feature seems to warn users if there is a change in a different configuration for repositories with many configs like nepal or medic-projects? Or for repositories with a single config, what if the change is in an unrelated folder like scripts?

Good point @kennsippell . Yes as you said the PR changes cause to evaluate the whole repo as a single configuration, but some repos holds multiple settings, I'll change that and only warn if the changes are related to the current folder where the tool is executed.

> Yes, this seems like a useful validation step for production deployments.

Got it. I will add the changes to detect whether the server is a production one or not, and if it is a non prod server, I think a good approach would be to perform the validations but just warn them, and log a message to tell the user how to skip the validations using the `--skip-git-check` flag if they prefer to avoid them (because the noisy warns or because the `git pull` execution delays the execution too much).

Eg. if I try to push configurations in a testing environment, the output will looks like this:

```
...
INFO Starting action: check-git…
INFO Fetching git upstream...
From github.com:medic/cht-core
   49d2e178f..0aa087c47  master                  -> origin/master
   36cf3db74..ec6017f28  add-db-config-get-endpoint -> origin/add-db-config-get-endpoint
   ...
WARN branch is behind upstream by 1 commit
INFO To skip the `check-git` action use `--skip-git-check`.
...
```

If production is detected, and no one of the flags `--skip-git-check` or `--force` are used, the CLI will execute the `check-git` action and the user will be prompted whether to continue or not if some of the validations fails.

**Comment by mrsarm** [comment]
**Ready for AT** again.

Added all the changes suggested in the last comment above, and also fixed the issues found [here](https://github.com/medic/medic-conf/pull/342#issuecomment-672748266).

**Comment by mrsarm** [comment]
@garethbowen as we discussed maybe it is better you to take again a look to the PR before moving to AT: https://github.com/medic/medic-conf/pull/342/files

**Comment by mrsarm** [comment]
### Summary

Here is a summary of what has been done:

- As the original description of the ticket, it adds a new default action called `check-git` that checks the current status of the git repository. It checks the following:
  - Whether the current folder has modified or untracked files. Because it only checks the current folder where the command is executed, it does not warn any error if it is a multi-config repository, where another folder inside the repo but outside the scope of the current folder has untracked changes.
  - It fetches the latest changes from upstream (without merge) and verify whether the local branch is in sync (ahead or behind).
  - In both cases `WARN` about the issue and allows the user to skip the process or continue.
- A new argument was added to skip the action, specially useful when `medic-conf` is executed whiting a script: `--skip-git-check`.
- It also supports the flag `--force`: the git verifications will be executed but only warn in case the repo is not in sync.
- Because may be annoying when developing (despite the flag to skip the action), it checks the instance URL first, and only performs the git checks if the URL seems to be a production one, eg. https://partnername.com, https://some-partner.medicmobile.org , ... In fact, what the process really does is to check whether the URL is a local one (not production) or one that looks like a testing environment, where the domain name (or its subdomains) have a word like `dev`, `dev-`, `test...`, in these cases the instance is assumed as a not production one and the checks are performed.

### Execution

Here is an example of how the action works when it find files untracked:

```
$ mmconf --url=http://admin:couch@prodenv.com:5984/medic
INFO Processing config in default. 
INFO Actions:
     - check-git
     - compile-app-settings
     ...
INFO Starting action: check-git… 
WARN There are changes in your local branch to be committed or not staged for commit. 
WARN Changes untracked or to be committed:
 M config/default/app_settings.json                                                                                                                                                                                                                                                                                       
 M config/default/forms/app/pregnancy_home_visit.xml                                                                                                                               
?? config/default/forms/contact/clinic-create.xlsx                                                                                                                                                                                                                                                       
?? config/default/forms/contact/health_center-edit.xlsx                                                                                                                            
                                                                                                                                                                                   
Are you sure you want to continue? [y/n]:
```

Here is how the process is skipped if non-production environment is detected:

```
$ mmconf --local
INFO Using local url from COUCH_URL environment variable: http://admin:****@localhost:5984/medic 
INFO Processing config in default. 
INFO Actions:
     - check-git
     ...
INFO Starting action: check-git… 
INFO No production environment detected: skipping check-git… 
INFO check-git complete.
...
```

**Comment by newtewt** [comment]
Hey  @mrsarm  I think this is ready to go.  I don't know that this really requires any documentation but I do have two call outs.  If your git state(repo,branch, etc...) have changes upstream or locally committed that are not within the folder you are working in. Then you will get that warning. Even though the check does perform on uncommitted files in the current dir.  

Secondly I agree with your production check and it should be something in people's minds that it isn't full-proof. 

Checked with git not installed and a warning shows
Checked that force accepts the warning.
Checked the skip flag works
Checked I can still upload if I get warned about changes.
Checked that changes are stopped if I `N` the warning.
Checked locally with ngrok and localhost to see the production checks.
Pushed changes to my test branch in a different folder. Was warned about the upstream changes.
Committed local changes in my test branch and was warned about the local changes.

**Comment by mrsarm** [comment]
@kennsippell is it too much to ask you or somebody from your team to test it from the usability point of view? do you think with the latest changes after your suggestions that were applied this is ready to merge? let me know if you think more changes are needed

**Comment by kennsippell** [comment]
Thanks for engaging @mrsam. 

A relevant update from app services on this: we have taken our first steps to transition away from manual deployments in production, so these checks hopefully won't be relevant for us too much longer. You can follow progress toward that objective in https://github.com/medic/app-services-team/issues/5. That said, they may impact things for our next few sprints.

> Medic is transitioning away from manual production deployments, and LG has transitioned away and uses a CI/CD pipeline. So over time, you'll see a higher percentage of experiences for which this is not relevant.


Nick's feedback here sounds relevant. It sounds like the warnings should be scoped down further so they aren't generating false positives:

> If your git state(repo,branch, etc...) have changes upstream or locally committed that are not within the folder you are working in. Then you will get that warning.

**Comment by mrsarm** [comment]
> If your git state(repo,branch, etc...) have changes upstream or locally committed that are not within the folder you are working in. Then you will get that warning.

Makes senses. There is a git command to check just the changes from upstream in the current folder, but I have to test it more carefully and implement the change, I leave here the syntax to not forget it when back to this:

    $ UPSTREAM="origin/master"
    $ git diff-tree --no-commit-id --name-only -r ..$UPSTREAM .

**Comment by mrsarm** [comment]
@newtewt the fix to check changes against upstream comparing only files from the current folder is done in the same `64-git-check` branch. Please check again.

**Comment by newtewt** [comment]
Dev/Local/Prod Check works
git not installed check works. 
changes in folder not committed shows the warning to continue or not. 
Checked I can still upload if I get warned about changes.
Checked that force accepts the warning.
Checked the skip flag works
Checked that changes are stopped if I N the warning.
Pushed changes to my test branch in a different folder. Was warned about the upstream changes.
Committed local changes in my test branch and was warned about the local changes.

And the check is restricted to the dir you are working at. I think this is ready to merge @mrsarm

**Comment by mrsarm** [comment]
Merged into master.
